name: mynpc
main: jb\kill
version: 1.0.3
api: [1.0.0]
load: POSTWORLD
author: cpera
commands:
  npc:
    description: orz
    usage: "/npc <gm/add/world/remove>"
    permission: fuckbear.xxo
  new:
    description: orz
    usage: "/new <gm/add/world/remove>"
    permission: fuckbear.xxo
permissions:
  fuckbear.xxo:
    description: "oo"
    default: op
  fuckbear.xxp:
    description: "oo"
    default: true
